handicap: 90
game_duration: 15
gift_compass: true
hunt_in_night: true
lang: "en_us"

en_us:
  gift_compass_name: "&3Compass to ruined portal"
  game_doesnt_start: "&4Game doesn't start!"
  enter_instructions: "Game will start, when somebody use &e/start&f (became survivor)"
  game_started: "&aGame starts! RUN, SURV, RUN!"
  handicup_ends: "Handicup ends after &3%s"
  handicup_doesnt_end: "&4Handicup doesn't end!"
  surv_die_before_hunt_starts: "&eSurv dies before hunt starts! Make fun of him!"
  hunt_starts: "&2Hunt began!"
  game_ends_after: "&4Survivor wins after %s"
  survivor_wins: "&2Survivor wins!"
  hunters_win: "&4Hunts win!"
  sec: "%d sec"
  min: "%d min"
  minsec: "%d min %d sec"

ru_ru:
  gift_compass_name: "&3Компас на разрушенный портал"
  game_doesnt_start: "&4Игра ещё не началась!"
  enter_instructions: "Игра начнётся когда кто-нибудь станет жужелицей (&e/start&f)"
  game_started: "&aИгра началась! БЕГИ, ЖУЖЕЛИЦА, БЕГИ!!!"
  handicup_ends: "Фора закончится через &3%s"
  handicup_doesnt_end: "&4Жужелице дана фора. Она ещё не закончилась!"
  surv_die_before_hunt_starts: "&eОно погибло до начала игры! Насмехайтесь над ним!"
  hunt_starts: "&2Открытие охоты!"
  game_ends_after: "&4Жужелица победит через %s"
  survivor_wins: "&2Жужелица победила!"
  hunters_win: "&4Охотники победили!"
  sec: "%d сек"
  min: "%d мин"
  minsec: "%d мин %d сек"
